// score is the variable name for percentage score
//grade is the variable name for the letter equal to the percentage score

let score;
let grade;
// The if else statements are used to condition the scores for a certain grade
if(score > 79){
    grade = 'A';
}
else if(score >= 60){
    grade = 'B';
}
 else if(score >= 49){
    grade = 'C';
 }
 else if(score >= 40){
    grade = 'D';
 }
 else{
    grade = 'E';
 }
 